### ISSUE TITLE
Gulp Chug errors on new node v4.0.0

### ISSUE THREAD

**Issue by danthewolfe** [robatron/gulp-chug#17]
I tried running my current gulp & gulp-chug file that works with 0.12 on the newly released 4.0.0 and got the following error output:

[09:14:05] Error in plugin 'gulp-chug'
Message:
    Gulpfile /Users/dwolfe2/Sites/adventure-coffee/game/assets/gulpfile.js exited with an error :(
[09:14:05] 'build' errored after 3.25 s
[09:14:05] Error: [object Object]
  at formatError (/Users/dwolfe2/.nvm/versions/node/v4.0.0/lib/node_modules/gulp/bin/gulp.js:169:10)
  at Gulp.<anonymous> (/Users/dwolfe2/.nvm/versions/node/v4.0.0/lib/node_modules/gulp/bin/gulp.js:195:15)
  at emitOne (events.js:82:20)
  at Gulp.emit (events.js:169:7)
  at Gulp.Orchestrator._emitTaskDone (/Users/dwolfe2/Sites/adventure-coffee/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
  at /Users/dwolfe2/Sites/adventure-coffee/node_modules/gulp/node_modules/orchestrator/index.js:275:23
  at finish (/Users/dwolfe2/Sites/adventure-coffee/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/Users/dwolfe2/Sites/adventure-coffee/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at finish (/Users/dwolfe2/Sites/adventure-coffee/node_modules/run-sequence/index.js:38:5)
  at Gulp.onError (/Users/dwolfe2/Sites/adventure-coffee/node_modules/run-sequence/index.js:45:4)
  at emitOne (events.js:82:20)
  at Gulp.emit (events.js:169:7)
  at Gulp.Orchestrator._emitTaskDone (/Users/dwolfe2/Sites/adventure-coffee/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
  at /Users/dwolfe2/Sites/adventure-coffee/node_modules/gulp/node_modules/orchestrator/index.js:275:23
  at finish (/Users/dwolfe2/Sites/adventure-coffee/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at DestroyableTransform.<anonymous> (/Users/dwolfe2/Sites/adventure-coffee/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4)
  at DestroyableTransform.f (/Users/dwolfe2/Sites/adventure-coffee/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
  at emitOne (events.js:82:20)
  at DestroyableTransform.emit (events.js:169:7)
  at sayErr (/Users/dwolfe2/Sites/adventure-coffee/node_modules/gulp-chug/index.js:40:18)
  at ChildProcess.<anonymous> (/Users/dwolfe2/Sites/adventure-coffee/node_modules/gulp-chug/index.js:172:17)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by mathesond2** [comment]
@robatron  is gulp-chug still being maintained? This issue was created 9 months ago and still has not been addressed...

**Comment by theiawolfe** [comment]
Assuming project is no longer maintained.
