### ISSUE TITLE
Error with rechoir / liftoff

### ISSUE THREAD

**Issue by mpuittinen** [robatron/gulp-chug#18]
I get the following error with gulp-chug in one of my (customer) projects:

Error: No module loader found for ".tmp.1443527063128.js".
    at Object.exports.prepare (/Users/mikael/repos/HappyOrNot/webshop/server/lambda-functions/HoN-cc-fingerprint/node_modules/gulp/node_modules/liftoff/node_modules/rechoir/index.js:18:11)
    at Liftoff.buildEnvironment (/Users/mikael/repos/HappyOrNot/webshop/server/lambda-functions/HoN-cc-fingerprint/node_modules/gulp/node_modules/liftoff/index.js:127:25)
    at Liftoff.<anonymous> (/Users/mikael/repos/HappyOrNot/webshop/server/lambda-functions/HoN-cc-fingerprint/node_modules/gulp/node_modules/liftoff/index.js:192:32)
    at module.exports (/Users/mikael/repos/HappyOrNot/webshop/server/lambda-functions/HoN-cc-fingerprint/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/Users/mikael/repos/HappyOrNot/webshop/server/lambda-functions/HoN-cc-fingerprint/node_modules/gulp/node_modules/liftoff/index.js:185:9)
    at /Users/mikael/repos/HappyOrNot/webshop/server/lambda-functions/HoN-cc-fingerprint/node_modules/gulp/node_modules/liftoff/index.js:159:9
    at /Users/mikael/repos/HappyOrNot/webshop/server/lambda-functions/HoN-cc-fingerprint/node_modules/gulp/node_modules/v8flags/index.js:91:14
    at /Users/mikael/repos/HappyOrNot/webshop/server/lambda-functions/HoN-cc-fingerprint/node_modules/gulp/node_modules/v8flags/index.js:38:7

The error seems to be related to the file naming of the temp file. Changing it to use _ instead of . as the delimiters fixes the issue.

**Comment by robatron** [comment]
This should be fixed now. See #14. Let me know if it's still an issue, and I can make that change. Thanks!
